version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: cd WebAppForDocker && docker build .

workflows:
  version: 2
  build:
    jobs:
      - build
