version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:8.11.1-browsers
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: cd WebAppForDocker && docker build -t "$DOCKER_CI_REGISTRY_HOST/webapp:v1" .
      - run:
          name: Run Tests
          command: echo Tests running
      - run:
          name: Docker login
          command: |
            docker login $DOCKER_CI_REGISTRY_HOST -u $DOCKER_CI_USER -p $DOCKER_CI_PASSWORD
      - run:
          name: Image deploy
          command: |
            docker push "$DOCKER_CI_REGISTRY_HOST/webapp:v1"

workflows:
  version: 2
  build:
    jobs:
      - build-and-deploy
